### PR TITLE
Backup compose files before overwriting

### LINKED ISSUE #33: Backup compose files before overwriting
We strongly recommend to not upgrade compose files manually, and rather use overrides to add own changes - this can be because of particularities in networking or anything else that is necessary. 

However this is not always the case, and we have had instances crash after being upgraded because of manual changes to docker-compose files. Some that come to mind (that have happened in either test or production instances) are: 
- updating networks in order to use docker swarm
- updating nginx certificate properties

My proposal is to make backups of the existent docker-compose files when upgrading. 
This can look like a `backups` folder, and we create a (timestamped?) backup with a snapshot of all docker-compose files (even ones not "owned" by the CHT) that are present in the folder passed to the upgrade-service. 
This can potentially help recovery and debugging.

### PR DESCRIPTION
**Pull request by nydr**
Resolves #33

### CODE REVIEW

File: src/containers.js [hunk 1]
```diff
@@ -15,6 +17,8 @@ const validComposeFile = async (contents) => {
   return valid;
 };
 
+const backupIsEnabled = () => process.env.CHT_BACKUP_COMPOSE_YML !== 'false';
```
Comment (dianabarsan) [inline src/containers.js:20]: I would go for strict equal to `true` rather than strict difference to `false`

File: src/containers.js [hunk 2]
```diff
@@ -38,19 +42,72 @@ const update = async (fileName, fileContents, install = false) => {
...
+      );
+    }
+  }
+};
+
+/**
+ * @param {string} dir Directory to check for files
+ * @returns {Promise<string[]>} Files in directory
+ */
+const getFilesInFolder = async (dir) => {
```
Comment (dianabarsan) [inline src/containers.js:99]: Please use `await` instead of `then` here. The function is already `async` and we use `await` all across this project.

File: test/e2e/utils.js [hunk 3]
```diff
@@ -168,14 +193,20 @@ const waitForServiceContainersUp = async () => {
   // try for 5 seconds
   let keepTrying = true;
   const killTimeout = setTimeout(() => keepTrying = false, 5000);
-  const files = await fs.promises.readdir(dockerComposeFolder);
+  const filenames = await fs.promises
+    .readdir(dockerComposeFolder, { withFileTypes: true })
+    .then((dirEntries) =>
```
Comment (dianabarsan) [inline test/e2e/utils.js:198]: Please don't `then` when you `await`. Please please please please.

File: test/e2e/utils.js [hunk 4]
```diff
@@ -221,6 +253,36 @@ const getServiceEnv = async (file, service, envVarName) => {
...
+  const lastBackupFolder = backupFolders.at(-1);
+  const dir = await fs.promises.readdir(path.resolve(backupFolder, lastBackupFolder));
+  for (const filePath of dir) {
+    if (filePath === filename) {
+      const fileContent = await fs.promises.readFile(
+        path.resolve(backupFolder, lastBackupFolder, filePath),
+        { 'encoding': 'utf-8' }
+      );
+      for (const line of fileContent.split('\n')) {
+        const matched = line.match(/image: \S+\/(?<service>[^:/]+):(?<version>\d\.\d\.\d)$/);
```
Comment (dianabarsan) [inline test/e2e/utils.js:276]: I wonder if you could just compare it with a file that we generate. I was thinking to using `setVersion` function from this file to return a string that we compare with entirely, instead of parsing lines.

**Review by dianabarsan — CHANGES_REQUESTED** [review]
Cool stuff! Thanks for this! 
I haven't had time to try this out yet, but I gave it a quick look through and left some minor comments inline.

File: src/containers.js (hunk 1 above)
Comment (nydr) [reply src/containers.js:20]: That would change default behaviour to off, is that desired?

File: src/containers.js [hunk 5]
```diff
@@ -38,19 +42,72 @@ const update = async (fileName, fileContents, install = false) => {
     return false;
   }
 
-  // write temp file, validate and then overwrite
   if (!await validComposeFile(fileContents)) {
     throw new Error(`Invalid docker-compose yml for file ${fileName}`);
   }
 
+  if (backupIsEnabled()) {
+    await backupYmlFiles();
```
[the remark this answers is not in the document]
Comment (nydr) [reply src/containers.js:50]: Agreed, much better name 👍

File: src/containers.js (hunk 1 above)
Comment (dianabarsan) [reply src/containers.js]: I guess you're right. We want default behavior to be on.

File: src/containers.js [hunk 6]
```diff
@@ -38,19 +42,72 @@ const update = async (fileName, fileContents, install = false) => {
...
+ * @returns {string} Name for folder e.g. 2023-07-17_131438_817_2Tjx
+ */
+const genBackupFolderName = () => {
+  const filefriendlyDatetime = new Date()
+    .toISOString()
+    .replace('T', '_')
+    .replaceAll(':', '')
+    .replace('.', '_')
+    .replace('Z', ''); // e.g. 2023-07-17_131438_817
+
```
[the remark this answers is not in the document]
Comment (nydr) [reply src/containers.js:71]: > Can this big chain be replaced with a single one with a regex?

It would have to be two lines unless we decide to always replace with the same character
```suggestion
    .replaceAll(/[T.]/g, '_')
    .replaceAll(/[Z:]/g, ''); // e.g. 2023-07-17_131438_817
```
```suggestion
    .replaceAll(/[T:.Z]/g, '_'); // e.g. 2023-07-17_13_14_38_817_
```

I find the first regexp here a bit less clear and prefer the original format, but am open for either

File: test/e2e/utils.js (hunk 4 above)
Comment (nydr) [reply test/e2e/utils.js]: Added in 994f6b8

File: README.md [hunk 7]
```diff
@@ -85,6 +85,7 @@ This is a list of all variables that can be used:
...
 | `CHT_NETWORK`              | no       | docker network to use for cht-core and cht-upgrade-service. Defaults to `cht-net`                                                                                                                                                                                                         | `cht-dev-4-alpha-net`                                                                |
+| `CHT_BACKUP_COMPOSE_FILES` | no       | Whether to backup yml files before overwriting. Can be `true` or `false` (default `true`).                                                                                                                                                                                               | `false`                                                                              |
```
Comment (latin-panda) [inline README.md:88]: Just for learning, is this made an option in the env variables mainly because of the unit tests? 
It doesn't look that this is consuming megas of space, and the process doesn't look heavy.

File: src/containers.js [hunk 8]
```diff
@@ -15,6 +17,8 @@ const validComposeFile = async (contents) => {
   return valid;
 };
 
+const backupIsEnabled = () => process.env.CHT_BACKUP_COMPOSE_FILES !== 'false';
```
Comment (latin-panda) [inline src/containers.js:20]: `isBackupEnabled = () => ` 
I think verb goes first 🤔

Just as you did with `hasBackupDir` from the utils file

File: src/containers.js [hunk 9]
```diff
@@ -38,19 +42,69 @@ const update = async (fileName, fileContents, install = false) => {
...
   return true;
 };
 
+
+/**
+ * Generates a new name containing date of creation and random characters to avoid most collisions
+ * @returns {string} Name for folder e.g. 2023-07-17_131438_817_2Tjx
+ */
+const genBackupFolderName = () => {
+  const filefriendlyDatetime = new Date()
```
Comment (latin-panda) [inline src/containers.js:65]:
```suggestion
  const fileFriendlyDateTime = new Date()
```
because js doesn't have types or reserved words for `filefriendly` and `datetime`, so we use [camelCase](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/#use-lowercamelcase-for-variables-properties-and-function-names)

File: src/containers.js [hunk 10]
```diff
@@ -38,19 +42,69 @@ const update = async (fileName, fileContents, install = false) => {
...
+
+/**
+ * @param {string} dir Directory to check for files
+ * @returns {string[]} Files in directory
+ */
+const getFilesInFolder = async (dir) => {
+  const dirEntries = await fs.promises.readdir(dir, { withFileTypes: true });
+  return dirEntries
+    .filter((dirEntry) => dirEntry.isFile())
+    .map((dirEntry) => dirEntry.name);
```
Comment (latin-panda) [inline src/containers.js:103]:
```suggestion
    .map(file => file.name);
```
At this point, we have only files, I think it's clearer like this 🤔

File: src/containers.js [hunk 11]
```diff
@@ -38,19 +42,69 @@ const update = async (fileName, fileContents, install = false) => {
...
+ */
+const backupComposeFiles = async () => {
+  const backupFolder = path.resolve(rootBackupFolder, genBackupFolderName());
+  await fs.promises.mkdir(backupFolder, { recursive: true });
+
+  const files = await getFilesInFolder(dockerComposeFilePath);
+  for (const filename of files) {
+    if (filename.endsWith('.yml')) {
+      await fs.promises.copyFile(
+        path.resolve(dockerComposeFilePath, filename),
```
Comment (latin-panda) [inline src/containers.js:88]: Maybe silly question, is it possible to eventually have a folder with yml files inside the `dockerComposeFilePath`? (other than the /backup one)

File: test/e2e/utils.js [hunk 12]
```diff
@@ -74,9 +99,9 @@ const dockerCommand = (files, ...params) => {
 };
 
 const serviceComposeCommand = (...args) => dockerCommand(DOCKER_COMPOSE_FILE, ...args);
-const testComposeCommand = (fileNames, ...args) => {
-  fileNames = Array.isArray(fileNames) ? fileNames : [fileNames];
-  const filePaths = fileNames
+const testComposeCommand = (filenames, ...args) => {
```
Comment (latin-panda) [inline test/e2e/utils.js:102]: Why changing from `fileNames` to `filenames`? 

Comment applies to any occurrence of `filename` in this PR 🙂

File: test/e2e/utils.js [hunk 13]
```diff
@@ -168,14 +193,17 @@ const waitForServiceContainersUp = async () => {
   // try for 5 seconds
   let keepTrying = true;
   const killTimeout = setTimeout(() => keepTrying = false, 5000);
-  const files = await fs.promises.readdir(dockerComposeFolder);
+  const dirEntries = await fs.promises.readdir(dockerComposeFolder, { withFileTypes: true });
+  const filenames = dirEntries
+    .filter((dirEntry) => dirEntry.isFile())
+    .map((dirEntry) => dirEntry.name);
```
Comment (latin-panda) [inline test/e2e/utils.js:199]:
```suggestion
    .map(file => file.name);
```

File: test/unit/file-utils.js [hunk 14]
```diff
@@ -0,0 +1,14 @@
+'use strict';
```
Comment (latin-panda) [inline test/unit/file-utils.js:1]: If we're going to have different utils. Then this can be in a utils folder and simplify the name `/test/unit/utils/file.js`

**Review by latin-panda — COMMENTED** [review]
Looks good! I have small comments and questions inline.

File: README.md (hunk 7 above)
Comment (nydr) [reply README.md:88]: We could change the tests so they're not dependent on this variable. I added it as this PR adds new requirements to the service (writable file system, disk space) so I wanted an option to disable it, but I'm happy to remove the option as it might be unnecessary complexity

File: test/e2e/utils.js (hunk 12 above)
Comment (nydr) [reply test/e2e/utils.js:102]: It's minor and either is technically correct but [nodejs](https://nodejs.org/api/fs.html) and [wikipedia](https://en.wikipedia.org/wiki/Filename) treat it as a single word so I went with that

File: src/containers.js (hunk 11 above)
Comment (nydr) [reply src/containers.js:88]: Ideally there's only going to be compose files, but since I'm not doing any cleanup I wanted to add a file extension check so I don't inadvertently backup large log files or something similar

File: test/e2e/utils.js (hunk 12 above)
Comment (latin-panda) [reply test/e2e/utils.js:102]: It looks weird to me 😅, but okay, it's readable

**Review by latin-panda — APPROVED** [review]
Thanks! LGTM

File: test/e2e/utils.js (hunk 12 above)
Comment (nydr) [reply test/e2e/utils.js:102]: I'm not too fussed either way; readability and consistency are more important. Let me know if you want me to change it 🙂

File: src/containers.js (hunk 1 above)
Comment (nydr) [reply src/containers.js]: By the way is `true`/`false` preferable to `1`/`0`? (or `yes`/`no`, `on`/`off` but I'd prefer to avoid those as they tend to increase confusion)

Comment (dianabarsan) [reply src/containers.js]: > By the way is true/false preferable to 1/0?

I would say yes.

File: src/containers.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (nydr) [reply src/containers.js]: PR updated using dashes, new format `2023-07-17-13-14-38-817-2Tjx`

**Comment by nydr** [comment]
FYI 01a35f1 silently disabled all unit tests, fixed in 1f8702f which also disables checking for tests in subfolders

File: test/e2e/utils.js [hunk 15]
```diff
@@ -221,6 +250,29 @@ const getServiceEnv = async (file, service, envVarName) => {
...
+  const dir = await fs.promises.readdir(path.resolve(backupFolder, lastBackupFolder));
+  for (const filePath of dir) {
+    if (filePath === filename) {
+      return fs.promises.readFile(
+        path.resolve(backupFolder, lastBackupFolder, filePath),
+        { 'encoding': 'utf-8' }
+      );
+    }
+  }
+  return Promise.reject(new Error(`Could not find file ${filename} in backup dir`));
```
Comment (dianabarsan) [inline test/e2e/utils.js:273]: You could just 
```suggestion
  throw new Error(`Could not find file ${filename} in backup dir`);
```

**Review by dianabarsan — APPROVED** [review]
I really appreciate this PR. It's simple work, but you treated it respectfully and paid attention to small details (like `fs.constants.UV_DIRENT_LINK`) and added quality within existent code. This makes me really happy. Thank you @nydr .
